### ISSUE TITLE
How to prepare custome patterns 

### ISSUE THREAD

**Issue by lengfei5** [abcucberkeley/LLSM_Processing_GUI#48]
Dear LLSM team, 

Thank you for such a great processing software specifically designed for large images.
We have images with 1-20 terabytes for each and we are try to run LLSM for our images.

One problem we got is that we have only .czi images with metadata within it and we don't know what exact information and which format we should extract from our .czi image to specify the "Custom Patterns" in the "Main Settings". 

Could you give us more tips what and how to prepare to set this parameter ?

Many thanks in advance.

Best,
Jingkui from IMP https://www.imp.ac.at/groups/elly-tanaka

**Comment by lengfei5** [comment]
Or should I convert our .czi file into .tiff as input for LLSM_Processing_GUI ?

**Comment by ruanxt** [comment]
Hi Jingkui, 

Thank you very much for your interest in our software! Currently, we only support Tiff and Zarr formats. We may add the support of .czi in the future, but because .czi format is a private data format and we have never worked with it before, we may need some time to figure it out. If you are familiar with .czi format, we recommend converting it to Zarr instead of Tiff if you are able to do the conversion by yourself, because Tiff has a poor performance for very large image data between 1-20 TB in your case. 

Best, 

Xiongtao

**Comment by lengfei5** [comment]
Dear Xiongtao @ruanxt, 

Many thanks for your quick answer.

I would try to convert our .czi format into Zarr and thanks again for the tip.

Another question we have is how to specify **"Channel Pattern"** or **"Custom Patterns"** in the "Main setting" (see below snapshot).
 
What metadata of images should be in the same folder as images to process ?
which file format should there for those metadata ? 
Is there any special naming of files for those metadata ?

Thank you in advance.

Best,
JIngkui 

![Screenshot 2024-03-15 at 10 39 50](https://github.com/abcucberkeley/LLSM_Processing_GUI/assets/24827756/95bb3303-1dc9-48d2-89c6-8b5896a1240b)

**Comment by ruanxt** [comment]
Hi JIngkui, 

Before addressing your questions, I recommend reading the documentation and trying out the demos if you haven't already. This will help you understand the parameters and setups better. I believe most of your questions will be answered once you've done this.

We have detailed documentation for the parameters and setups for the running, which can be accessed here: [https://github.com/abcucberkeley/LLSM_Processing_GUI/wiki](https://github.com/abcucberkeley/LLSM_Processing_GUI/wiki). Also, for the non-GUI version, we have several demos to help users in understanding the workflows with a demo dataset. The demos are [here](https://github.com/abcucberkeley/LLSM5DTools/tree/main/demos). If you have Matlab R2022b or a newer version installed, consider running the demos listed, consider running the demos listed [here](https://github.com/abcucberkeley/LLSM5DTools?tab=readme-ov-file#demos).

Please feel free to let us know if you have questions or issues when running the software. 

Best, 

Xiongtao
